# -*- coding: utf-8 -*-
"""Merging File function Script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cHDzF2TM0u97fwDUEC5c9t0YsOeRfYr3
"""

import os
import pandas as pd

def merge_csv_files(input_dir, output_file):
    # Get a list of all CSV files in the input directory
    csv_files = [f for f in os.listdir(input_dir) if f.endswith('.csv')]

    # Concatenate all CSV files into a single DataFrame and sort by participant number
    dataframes = []
    for csv_file in csv_files:
        csv_path = os.path.join(input_dir, csv_file)
        dataframe = pd.read_csv(csv_path)
        dataframes.append(dataframe)
    merged_dataframe = pd.concat(dataframes, ignore_index=True)
    merged_dataframe = merged_dataframe.sort_values('Participant_Number')

    # Write the merged DataFrame to a CSV file
    merged_dataframe.to_csv(output_file, index=False)


    # Write the merged DataFrame to a CSV file
    merged_dataframe.to_csv(output_file, index=False)
input_dir = 'C:/Users/Zain Ali/Desktop/New folder/Testing group'
output_file = 'Control_Group_data.csv'
merge_csv_files(input_dir, output_file)

