# -*- coding: utf-8 -*-
"""Missing Values Fill by Interpolation Script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FIMs0iayjLaAy5jHoxtGxjcX8OspQHLp
"""

import pandas as pd
import glob
participant_list = range(1, 61)

def process_files(participant_num):
    # Find all files for the given participant number
    file_pattern = f"*participant_{participant_num}_trial_*"
    file_list = glob.glob(file_pattern)

    # Loop through all files for the participant
    for file_name in file_list:
        # Load the file as a pandas dataframe
        df = pd.read_csv(file_name)

        # Loop through all columns in the dataframe and convert to float64 if datatype is object
        for col in df.columns:
            if df[col].dtype != 'float64':
                if df[col].dtype == 'object':
                    df[col] = df[col].str.replace(',', '.')
                try:
                    df[col] = pd.to_numeric(df[col], errors='raise').astype('float64')
                except:
                    continue

      
        # perform linear interpolation on the dataframe
        df = df.interpolate(method='linear', axis=0)

        # perform cubic spline interpolation on the dataframe
        df= df.interpolate(method='cubic', axis=0)
        df.fillna(method="bfill", inplace=True)
        output_file_name = f"Proceed_{file_name}"
        df.to_csv(output_file_name, index=False)
        
for participant_num in participant_list:
    process_files(participant_num)



